export const types = Object.freeze({
  /* People */
  START_FETCHING_PEOPLE: "START_FETCHING_PEOPLE",
  STOP_FETCHING_PEOPLE: "STOP_FETCHING_PEOPLE",
  FILL_PEOPLE: "FILL_PEOPLE",
  SET_FETCHING_PEOPLE_ERROR: "SET_FETCHING_PEOPLE_ERROR",

  FETCH_PEOPLE_ASYNC: "FETCH_PEOPLE_ASYNC",

  /* Person */
  START_FETCHING_PERSON: "START_FETCHING_PERSON",
  STOP_FETCHING_PERSON: "STOP_FETCHING_PERSON",
  FILL_PERSON_PROFILE: "FILL_PERSON_PROFILE",
  SET_FETCHING_PERSON_ERROR: "SET_FETCHING_PERSON_ERROR",
  CLEAR_PERSON_PROFILE: "CLEAR_PERSON_PROFILE",

  FETCH_PERSON_ASYNC: "FETCH_PERSON_ASYNC",
});
