export const types = Object.freeze({
  /* Films */
  START_FETCHING_FILMS: "START_FETCHING_FILMS",
  STOP_FETCHING_FILMS: "STOP_FETCHING_FILMS",
  FILL_FILMS: "FILL_FILMS",
  SET_FETCHING_FILMS_ERROR: "SET_FETCHING_FILMS_ERROR",

  FETCH_FILMS_ASYNC: "FETCH_FILMS_ASYNC",

  /* Film */
  START_FETCHING_FILM: "START_FETCHING_FILM",
  STOP_FETCHING_FILM: "STOP_FETCHING_FILM",
  FILL_FILM_PROFILE: "FILL_FILM_PROFILE",
  SET_FETCHING_FILM_ERROR: "SET_FETCHING_FILM_ERROR",
  CLEAR_FILM_PROFILE: "CLEAR_FILM_PROFILE",

  FETCH_FILM_ASYNC: "FETCH_FILM_ASYNC",
});
